config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#locale_redirect', as: :root

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    # Protect against timing attacks:
    # - See https://codahale.com/a-lesson-in-timing-attacks/
    # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
    # - Use & (do not use &&) so that it doesn't short circuit.
    # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end if Rails.env.production?
  mount Sidekiq::Web, at: '/sidekiq'

  scope '/:locale' do
    get '/' => 'home#index', as: :home
    get '/faq' => 'home#faq', as: :faq
    get '/about-us' => 'home#about_us', as: :about_us
    get '/maintenance'=> 'home#maintenance'

    resources :signatures, only: [:index, :new, :create] do
      get 'page/:page', action: :index, on: :collection
      get 'thank-you', on: :collection
      get ':token/confirm', on: :collection,  action: :confirm, as: :confirm
      get 'counts', on: :collection,  action: :counts, format: :json
    end

    resources :countries, only: [:show], param: :country_code do
      get 'signature_counts', on: :member, format: :json
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :display_maintenance_page, only: :maintenance
  before_action :fetch_current_country_code, only: :index
  caches_action :index, cache_path: -> { { country_code: @country_code } }, expires_in: 5.minutes
  caches_action :about_us, :faq, expires_in: 10.minutes

  def locale_redirect
    # the redirect is handled by set_locale
  end

  def index
    @signature_count_for_country = Signature.cached_count_for_country_code(@country_code)
    @top_places_for_country = fetch_top_places_for_country(@country_code, @signature_count_for_country)
    @signature_count = Signature.cached_count_total
  end

  def maintenance
    redirect_to home_path unless maintenance_page_enabled?
  end

  protected

  def fetch_current_country_code
    ip_location = fetch_ip_location
    return unless ip_location
    @country_code = ip_location.country&.iso_code
  end

  def fetch_top_places_for_country(country_code, signature_count_for_country)
    if country_code && signature_count_for_country.positive?
      Signature.cached_count_by_place_for_country(country_code, 4)
    end
  end
end

app/views/home/_share_petition.html.erb
<div class="container share-petition">
  <div class="row text-center">
    <div class="col-6 col-md-3 share-text">
      Share petition on:
    </div>
    <div class="col-6 col-md-3 facebook-share">
      <%= link_to(facebook_sharing_url, rel: 'external', target: '_blank', class: 'facebook') do
        fa_icon('facebook', text: 'Facebook').html_safe
      end %>
    </div>
    <div class="col-6 col-md-3 twitter-share">
      <%= link_to(twitter_sharing_url, rel: 'external', target: '_blank', class: 'twitter') do
        fa_icon('twitter', text: 'Twitter').html_safe
      end %>
    </div>
    <div class="col-6 col-md-3">
      <%= mail_to('', subject: '100MillionVoices campaign', body: email_share_body, class: 'email') do
        fa_icon('envelope-o', text: 'Email').html_safe
      end %>
    </div>
  </div>
</div>

app/views/home/about_us.html.erb
<div class="about-us">
  <h1 class="lead text-center"><%= t('links.about_us') %></h1>

  <p><%= t('about_us.para_1') %></p>
  <p><%= t('about_us.para_2') %></p>
  <p><%= t('about_us.para_3_html', petition_link: link_to(t('about_us.petition'), home_path),
           faq_link: link_to(t('links.faq'), faq_path),
           sign_petition_link: link_to(t('about_us.sign_the_petition'), new_signature_path)) %></p>
</div>

<div class="breadcrumb-container">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to(t('links.home').downcase, home_path) %></li>
    <li class="breadcrumb-item active"><%= t('links.about_us').mb_chars.downcase %></li>
  </ol>
</div>

app/views/home/faq.html.erb
<div class="faqs">
  <h1 class="lead text-center"><%= t('links.faq') %></h1>

  <% I18n.t('faq').values.each do |question_answer| %>
    <%= content_tag :p, question_answer[:question_html].html_safe, class: 'question lead' %>
    <%= content_tag :p, question_answer[:answer_html].html_safe, class: 'answer' %>
  <% end %>
</div>

<div class="breadcrumb-container">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to(t('links.home').downcase, home_path) %></li>
    <li class="breadcrumb-item active"><%= t('links.faq').downcase %></li>
  </ol>
</div>

app/views/home/index.html.erb
<div class="petition-text">
  <% I18n.t('home.petition').values.each do |para| %>
    <%= content_tag :p, para.html_safe, class: 'lead' %>
  <% end %>

  <p class="petition-signer">
    <em><%= link_to(t('site_name', default: '100MillionVoices'), about_us_path) %></em><br>
  </p>
  <p class="petition-date">
    <small class="text-muted"><%= petition_date %></small>
  </p>
</div>

<div class="row signature-counts">
  <% if @signature_count_for_country %>
    <div class="text-center counter-block col-md-12 col-lg-6">
      <%= link_to(country_path(@country_code.downcase)) do %>
        <div class="counter country-counter">
          <small class="text-muted counter-text">
            <%= t('home.signatures_from', country: country_from_country_code(@country_code)) %>
          </small>
          <div class="counter-number" data-country="<%= @country_code %>" data-count="<%= @signature_count_for_country %>">
            <%= number_with_delimiter(@signature_count_for_country) %>
          </div>
        </div>
      <% end -%>
    </div>
  <% end -%>

  <div class="text-center counter-block col-md-12 col-lg-6">
    <%= link_to(signatures_path) do %>
      <div class="counter">
        <small class="text-muted counter-text"><%= t('home.total_signatures') %></small>
        <div class="counter-number" data-country="ALL" data-count="<%= @signature_count %>">
          <%= number_with_delimiter(@signature_count) %>
        </div>
      </div>
    <% end -%>
  </div>

  <% if @top_places_for_country %>
    <div class="text-center top-places col-md-12 col-lg-6">
      <%= link_to(country_path(@country_code.downcase)) do %>
        <% @top_places_for_country.each do |place, count| %>
          <div class="top-places-list-count">
            <span><%= place %></span>
            <span class="signature-count" data-place="<%= place %>" data-count="<%= count %>">
              <%= number_with_delimiter(count) %>
            </span>
          </div>
        <% end -%>
      <% end -%>
    </div>
  <% end -%>

  <div class="text-center counter-block sign-petition-block col-md-12 col-lg-<%= @signature_count_for_country && !@top_places_for_country ? '12' : '6' %>">
    <%= link_to(fa_icon('pencil', text: t('home.sign_petition')).html_safe, new_signature_path, class: 'btn btn-lg btn-secondary') %>
  </div>
</div>

<%= render 'share_petition' %>

<div class="breadcrumb-container">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active"><%= t('links.home').downcase %></li>
  </ol>
</div>