config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#locale_redirect', as: :root

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    # Protect against timing attacks:
    # - See https://codahale.com/a-lesson-in-timing-attacks/
    # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
    # - Use & (do not use &&) so that it doesn't short circuit.
    # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end if Rails.env.production?
  mount Sidekiq::Web, at: '/sidekiq'

  scope '/:locale' do
    get '/' => 'home#index', as: :home
    get '/faq' => 'home#faq', as: :faq
    get '/about-us' => 'home#about_us', as: :about_us
    get '/maintenance'=> 'home#maintenance'

    resources :signatures, only: [:index, :new, :create] do
      get 'page/:page', action: :index, on: :collection
      get 'thank-you', on: :collection
      get ':token/confirm', on: :collection,  action: :confirm, as: :confirm
      get 'counts', on: :collection,  action: :counts, format: :json
    end

    resources :countries, only: [:show], param: :country_code do
      get 'signature_counts', on: :member, format: :json
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir="<%= text_direction %>">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <% if request.get? %>
      <% I18n.available_locales.each do |locale| %>
        <link rel="alternate" href="<%= url_for_locale(locale) %>" hreflang="<%= locale %>" />
      <% end -%>
      <% if request.path == home_path(params[:locale]) %>
        <link rel="alternate" href="<%= root_url(locale: nil) %>" hreflang="x-default" />
      <% end -%>
    <% end -%>

    <title>100MillionVoices</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <% if rtl? %>
      <%= stylesheet_link_tag 'application-rtl', media: 'all' %>
    <% end %>
    <%= javascript_include_tag 'application' %>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <%= yield :head %>
  </head>

  <body>
    <header class="navbar navbar-left bg-warning text-white" data-delimiter="<%= t('number.format.delimiter') %>">
      <div class="navbar-header">
        <%= link_to(home_path, class: 'logo-link') do %>
          <div class="logo"></div>
        <% end -%>
        <div class="no-logo">
        <h2 class="header-text">
          <%= t('heading_html') %>
        </h2>
        <div class="dropdown text-right">
          <button class="dropbtn"><%= current_language %></button>
          <div class="dropdown-content">
            <% locales.each do |locale, language| %>
              <% if I18n.available_locales.exclude?(locale.to_sym) %>
                <div class="language unavailable-language"><%= language %></div>
              <% elsif locale != params[:locale] %>
                <%= link_to(url_for_locale(locale)) do %>
                  <div class="language"><%= language %></div>
                <% end %>
              <% else %>
                <div class="language selected-language"><em><%= language %></em></div>
              <% end %>
            <% end -%>
          </div>
        </div>
        </div>
      </div>
    </header>

    <div class="container-fluid main">
      <%= yield %>
    </div>

    <footer class="footer text-muted">
      <div class="container-fluid">
        <ul class="footer-links">
          <li><%= link_to(t('links.home'), home_path) %></li>
          <li><%= link_to(t('links.sign_petition'), new_signature_path) %></li>
          <li><%= link_to(t('links.signatures'), signatures_path) %></li>
          <li><%= link_to(t('links.faq'), faq_path) %></li>
          <li><%= link_to(t('links.about_us'), about_us_path) %></li>
          <li>
            <a href="https://medium.com/@100MillionVoice" rel="external" target="_blank">
              <%= t('links.blog') %>
            </a>
          </li>
          <li>
            <a href="mailto:help@100millionvoices.org" rel="external">
              <i class="fa fa-envelope-o" aria-hidden="true"></i> <%= t('links.contact') %>
            </a>
          </li>
          <li>
            <a href="https://twitter.com/100MillionVoice" rel="external" target="_blank">
              <i class="fa fa-twitter" aria-hidden="true"></i>
              <%= t('sharing.twitter', default: 'Twitter') %>
            </a>
          </li>
        </ul>
      </div>
    </footer>

    <% if country_page? %>
      <%= javascript_include_tag 'country-updater' %>
    <% elsif signature_counts_update_page? %>
      <%= javascript_include_tag 'auto-updater' %>
    <% elsif sign_petition_page? && !captcha_disabled? %>
      <%= javascript_include_tag 'recaptcha' %>
      <script src="https://www.google.com/recaptcha/api.js?hl=<%= I18n.locale %>" async defer></script>
    <% end %>
  </body>
</html>